services:
  db:
    image: postgres:15
    container_name: rtc-db
    environment:
      POSTGRES_DB: rtc_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NewStrong@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rtc-bus
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DB_HOST: rtc-db
      DB_NAME: rtc_booking
      DB_USER: postgres
      DB_PASSWORD: NewStrong@123
    restart: always

volumes:
  pgdata:
