apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtc-bus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rtc-bus-app
  template:
    metadata:
      labels:
        app: rtc-bus-app
    spec:
      containers:
      - name: rtc-bus-app
        image: rtc01.azurecr.io/rtc-bus-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: DB_HOST
          value: rtc-db
        - name: DB_NAME
          value: rtc
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
